-- Vectra Watch — esquema inicial seguro
-- Execute no SQL Editor do Supabase antes de iniciar o servidor.

create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  phone text not null unique check (phone ~ '^(84|85|86|87)[0-9]{7}$'),
  pin_hash text not null,
  ref_code text not null unique,
  sponsor_id uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.wallets (
  user_id uuid primary key references public.users(id) on delete cascade,
  available numeric(14,2) not null default 0 check (available >= 0),
  bonus numeric(14,2) not null default 50 check (bonus >= 0),
  locked numeric(14,2) not null default 0 check (locked >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.missions (
  id bigint generated by default as identity primary key,
  category text not null,
  title text not null,
  youtube_id text not null,
  reward numeric(14,2) not null check (reward > 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.mission_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  mission_id bigint not null references public.missions(id) on delete cascade,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.mission_completions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  mission_id bigint not null references public.missions(id) on delete cascade,
  completion_day date not null,
  reward numeric(14,2) not null,
  created_at timestamptz not null default now(),
  unique (user_id, mission_id, completion_day)
);

create table if not exists public.transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  kind text not null check (kind in ('deposit','withdrawal','mission_reward','referral_reward')),
  amount numeric(14,2) not null check (amount > 0),
  status text not null check (status in ('pending','approved','rejected','completed')),
  operator text,
  phone text,
  external_ref text,
  parent_tx_id uuid references public.transactions(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists transactions_external_ref_unique
  on public.transactions(external_ref)
  where external_ref is not null;

create unique index if not exists referral_reward_per_parent
  on public.transactions(parent_tx_id)
  where kind = 'referral_reward' and parent_tx_id is not null;

create index if not exists transactions_user_created_idx
  on public.transactions(user_id, created_at desc);

create index if not exists mission_runs_user_started_idx
  on public.mission_runs(user_id, started_at desc);

alter table public.users enable row level security;
alter table public.wallets enable row level security;
alter table public.missions enable row level security;
alter table public.mission_runs enable row level security;
alter table public.mission_completions enable row level security;
alter table public.transactions enable row level security;

-- O frontend nunca recebe a service-role key. Todas as operações passam pelo servidor.

create or replace function public.claim_mission(p_user_id uuid, p_run_id uuid)
returns table(reward numeric, new_available numeric)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_run public.mission_runs%rowtype;
  v_mission public.missions%rowtype;
  v_day date;
begin
  select * into v_run
  from public.mission_runs
  where id = p_run_id and user_id = p_user_id
  for update;

  if not found then
    raise exception 'RUN_NOT_FOUND';
  end if;

  if v_run.completed_at is not null then
    raise exception 'RUN_ALREADY_COMPLETED';
  end if;

  if v_run.started_at > now() - interval '10 seconds' then
    raise exception 'WATCH_TIME_NOT_REACHED';
  end if;

  select * into v_mission
  from public.missions
  where id = v_run.mission_id and active = true;

  if not found then
    raise exception 'MISSION_INACTIVE';
  end if;

  v_day := (now() at time zone 'Africa/Maputo')::date;

  insert into public.mission_completions(user_id, mission_id, completion_day, reward)
  values (p_user_id, v_mission.id, v_day, v_mission.reward);

  update public.mission_runs
  set completed_at = now()
  where id = p_run_id;

  update public.wallets
  set available = available + v_mission.reward,
      updated_at = now()
  where user_id = p_user_id
  returning available into new_available;

  insert into public.transactions(user_id, kind, amount, status, metadata)
  values (
    p_user_id,
    'mission_reward',
    v_mission.reward,
    'completed',
    jsonb_build_object('mission_id', v_mission.id, 'run_id', p_run_id)
  );

  reward := v_mission.reward;
  return next;
exception
  when unique_violation then
    raise exception 'MISSION_ALREADY_COMPLETED_TODAY';
end;
$$;

create or replace function public.request_withdrawal(
  p_user_id uuid,
  p_amount numeric,
  p_phone text,
  p_operator text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_wallet public.wallets%rowtype;
  v_tx uuid;
begin
  if p_amount < 400 then
    raise exception 'MIN_WITHDRAWAL_400';
  end if;

  if p_phone !~ '^(84|85|86|87)[0-9]{7}$' then
    raise exception 'INVALID_PHONE';
  end if;

  select * into v_wallet
  from public.wallets
  where user_id = p_user_id
  for update;

  if not found or v_wallet.available < p_amount then
    raise exception 'INSUFFICIENT_AVAILABLE_BALANCE';
  end if;

  update public.wallets
  set available = available - p_amount,
      locked = locked + p_amount,
      updated_at = now()
  where user_id = p_user_id;

  insert into public.transactions(user_id, kind, amount, status, phone, operator)
  values (p_user_id, 'withdrawal', p_amount, 'pending', p_phone, p_operator)
  returning id into v_tx;

  return v_tx;
end;
$$;

create or replace function public.approve_deposit(p_tx_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_tx public.transactions%rowtype;
  v_user public.users%rowtype;
  v_commission numeric(14,2);
begin
  select * into v_tx
  from public.transactions
  where id = p_tx_id and kind = 'deposit'
  for update;

  if not found then
    raise exception 'DEPOSIT_NOT_FOUND';
  end if;

  if v_tx.status <> 'pending' then
    raise exception 'DEPOSIT_ALREADY_PROCESSED';
  end if;

  update public.wallets
  set available = available + v_tx.amount,
      updated_at = now()
  where user_id = v_tx.user_id;

  update public.transactions
  set status = 'approved', updated_at = now()
  where id = p_tx_id;

  select * into v_user from public.users where id = v_tx.user_id;

  if v_user.sponsor_id is not null then
    v_commission := round(v_tx.amount * 0.10, 2);

    insert into public.transactions(
      user_id, kind, amount, status, parent_tx_id, metadata
    )
    values (
      v_user.sponsor_id,
      'referral_reward',
      v_commission,
      'completed',
      p_tx_id,
      jsonb_build_object('referred_user_id', v_tx.user_id)
    );

    update public.wallets
    set available = available + v_commission,
        updated_at = now()
    where user_id = v_user.sponsor_id;
  end if;
end;
$$;

create or replace function public.transition_withdrawal(
  p_tx_id uuid,
  p_action text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_tx public.transactions%rowtype;
begin
  select * into v_tx
  from public.transactions
  where id = p_tx_id and kind = 'withdrawal'
  for update;

  if not found then
    raise exception 'WITHDRAWAL_NOT_FOUND';
  end if;

  if v_tx.status <> 'pending' then
    raise exception 'WITHDRAWAL_ALREADY_PROCESSED';
  end if;

  if p_action = 'approve' then
    update public.wallets
    set locked = locked - v_tx.amount,
        updated_at = now()
    where user_id = v_tx.user_id;

    update public.transactions
    set status = 'approved', updated_at = now()
    where id = p_tx_id;

  elsif p_action = 'reject' then
    update public.wallets
    set locked = locked - v_tx.amount,
        available = available + v_tx.amount,
        updated_at = now()
    where user_id = v_tx.user_id;

    update public.transactions
    set status = 'rejected', updated_at = now()
    where id = p_tx_id;
  else
    raise exception 'INVALID_ACTION';
  end if;
end;
$$;

insert into public.missions(category, title, youtube_id, reward)
select * from (values
  ('Sétima Arte - Trailer', 'Gladiador II — Trailer Oficial', '4rgYUipGJNo', 85.00::numeric),
  ('Videoclipe Oficial', 'Burna Boy — City Boys', 'd6C0bNDq0Z4', 70.00::numeric),
  ('Cinema Africano', 'Mostra Independente — Seleção do Dia', 'kJQP7kiw5Fk', 95.00::numeric),
  ('Novo Artista', 'Lançamento Revelação — Monitoria de Som', 'kJQP7kiw5Fk', 60.00::numeric)
) as seed(category, title, youtube_id, reward)
where not exists (select 1 from public.missions);


-- SECURITY: funções financeiras SECURITY DEFINER são internas ao servidor.
-- O Postgres concede EXECUTE a PUBLIC por padrão; revogamos explicitamente.
revoke execute on function public.claim_mission(uuid, uuid) from public, anon, authenticated;
revoke execute on function public.request_withdrawal(uuid, numeric, text, text) from public, anon, authenticated;
revoke execute on function public.approve_deposit(uuid) from public, anon, authenticated;
revoke execute on function public.transition_withdrawal(uuid, text) from public, anon, authenticated;

grant execute on function public.claim_mission(uuid, uuid) to service_role;
grant execute on function public.request_withdrawal(uuid, numeric, text, text) to service_role;
grant execute on function public.approve_deposit(uuid) to service_role;
grant execute on function public.transition_withdrawal(uuid, text) to service_role;
